### ISSUE TITLE
Pie charts seem broken.

### ISSUE THREAD

**Issue by hammackj** [topfunky/gruff#178] opened 2018-05-06 21:29 UTC
Hi

I recently updated gems/etc and it seems pie charts no longer work. This is the stacktrace from my application that uses gruff. Not sure what would need to be changed in the call to draw for this to work, I haven't looked at rmagick.

-Jacob

```
/Users/hammackj/.gem/ruby/2.4.0/gems/gruff-0.7.0/lib/gruff/pie.rb:212:in `draw': non-conforming drawing primitive definition `ellipse' @ error/draw.c/DrawImage/3591 (Magick::ImageMagickError)
	from /Users/hammackj/.gem/ruby/2.4.0/gems/gruff-0.7.0/lib/gruff/pie.rb:212:in `trigger_final_draw'
	from /Users/hammackj/.gem/ruby/2.4.0/gems/gruff-0.7.0/lib/gruff/pie.rb:78:in `draw'
	from /Users/hammackj/.gem/ruby/2.4.0/gems/gruff-0.7.0/lib/gruff/base.rb:444:in `to_blob'
	from /Users/hammackj/Projects/hammackj/public/risu/lib/risu/models/item.rb:282:in `risks_by_service_graph'
	from /Users/hammackj/Projects/hammackj/public/risu/lib/risu/base/graph_template_helper.rb:53:in `risks_by_service_graph_page'
	from /Users/hammackj/Projects/private/Assessments/2018/pmc/hipaa_exec_summary.rb:236:in `render'
	from /Users/hammackj/Projects/hammackj/public/risu/lib/risu/base/templater.rb:61:in `block in generate'
	from /Users/hammackj/.gem/ruby/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:236:in `initialize'
	from /Users/hammackj/.gem/ruby/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:142:in `new'
	from /Users/hammackj/.gem/ruby/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:142:in `generate'
	from /Users/hammackj/Projects/hammackj/public/risu/lib/risu/base/templater.rb:56:in `generate'
	from /Users/hammackj/Projects/hammackj/public/risu/lib/risu/cli/application.rb:425:in `run'
	from /Users/hammackj/Projects/hammackj/public/risu/bin/risu:32:in `<main>'
```

**Comment by Hermanverschooten** [comment] 2018-05-07 09:13
I have the same issue with `line`.  But seeing the last commit on this gem dates from 1 june 2016, I am wondering if this gem is still alive.

**Comment by noraj** [comment] 2020-04-05 18:29
seems not be fix with the last release

**Comment by Watson1978** [comment] 2020-04-06 12:56
＠noraj Can you provide reproducible code, etc.? It is helpful for investigating this issue.

**Comment by noraj** [comment] 2020-04-06 22:16
Hum not broken like the post from 2018 were it was simply not working, but broken because they don't do what it's expected. For example with code see https://github.com/topfunky/gruff/issues/179

**Comment by Watson1978** [comment] 2020-04-07 13:34
```ruby
require 'gruff'

g3 = Gruff::Pie.new
g3.data :Yes, 10.4 # => 10
g3.data :No, 89.6 # => 90
g3.write('test.png')
```

On my macOS, the above code generates following image without error.
![test](https://user-images.githubusercontent.com/199156/78674952-5548c180-791f-11ea-8153-bb328247f359.png)

I'm guessing this issue is related to ImageMagick version...

@noraj Can you provide the version which you're using and other useful information (platform, etc) to reproduce?

**Comment by noraj** [comment] 2020-04-07 22:40
> Hum not broken like the post from 2018 were it was simply not working, but broken because they don't do what it's expected. For example with code see #179

Sorry I wasn't clear enough, Pie chart are not broken anymore like in 2018. There is no crash anymore.
But as explain in #179, pie charts (and nearly all charts except side_stacked_bar, bar, side_bar) are not handling float values.

So you may close this issue I think.

**Comment by Watson1978** [comment] 2020-04-10 16:37
Thanks, I will close this.
Feel free to re-open if you needed :)

**Closed by Watson1978** 2020-04-10 16:37 UTC
